### ISSUE TITLE
[FE] admin 페이지 앨범 등록 구현

### ISSUE THREAD

**Issue by chaeryeon823** [boostcampwm-2024/web18-inear#69]
## ✨ 기능에 대한 기대
관리자는 최신 앨범 정보를 등록할 수 있다

## 🔗 관련 링크
없음.

## 📋 구현/작업 목록
- 현재 `manager`에서 `admin`으로 변경
- 앨범 정보를 입력 받는다
  - 앨범 제목
  - 앨범 아티스트
  - 앨범 커버
  - 앨범 태그
  - 재생할 순서에 맞는 노래 제목
  - 노래 개수
  - 노래 마다 연주자/가수, 작곡가/작사가, 프로듀서, 출처
- 세션을 생성할 시간을 입력 받는다
  - 세션 생성 년/월/일/시/분

## 📆 구현 계획
- Admin 페이지에 input 태그로 입력 받기

**Comment by yoonseo-han** [comment]
노래마다 연주자/가수, 작곡가/작사가, 프로듀서, 출처는 array의 형식으로 전달이 되는걸까요?

Array로 노래를 관리해주는거면 다음 인터페이스로 관리를 해주는 방향은 어떨까요?
```ts
interface SongInfo {
  title: string;
  trackNumber: number; //몇번째 트랙인지
  // 기타 필요한 곡 정보: 연주자/가수, 작곡가/작사가, 프로듀서, 출처
}
```

그러고 해당 정보를 앨범에 삽입하여 전달하는 형식입니다
```js
export class AlbumDto {
  title: string;
  artist: string;
  sessionDate: Date;
  albumImage: URL;
  songs: SongInfo[];  // 수록곡 정보 포함
}
```

**Comment by chaeryeon823** [comment]
`SongInfo`에 노래 순서 추가하는 방식으로 진행하겠습니다 🔥
